# Generated by Django 5.0.6 on 2024-06-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='items/')),
                ('titulo', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('telefono', models.CharField(max_length=10)),
                ('Email', models.CharField(max_length=50)),
            ],
        ),
    ]
