# Generated by Django 5.0.6 on 2024-06-28 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mirasolapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servicios',
            new_name='Servicio',
        ),
    ]
