# Generated by Django 5.0.6 on 2024-06-28 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mirasolapp', '0002_rename_servicios_servicio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
