# Generated by Django 5.0.6 on 2024-06-28 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mirasolapp', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
