# Generated by Django 5.0.6 on 2024-07-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirasolapp', '0007_alter_servicio_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id_noticia', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='noticias')),
                ('titular', models.CharField(max_length=20)),
                ('breve_desc', models.CharField(max_length=30)),
                ('noticia', models.CharField(max_length=100)),
            ],
        ),
    ]
