# Generated by Django 5.0.6 on 2024-07-01 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mirasolapp', '0008_noticia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Noticia',
        ),
    ]
