# Generated by Django 5.0.6 on 2024-07-10 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirasolapp', '0011_alter_noticia_fecha_alter_noticia_id_noticia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='id_noticia',
            field=models.CharField(max_length=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='id_servicio',
            field=models.CharField(max_length=1, primary_key=True, serialize=False),
        ),
    ]
